name = "GTAPv7"
uuid = "17bf7c9d-bd82-4e09-a8b5-dac70c0d12c3"
authors = ["Maros Ivanic"]
version = "1.0.0-DEV"

[deps]
ComputableGeneralEquilibriumHelpers = "b2f8801f-5e08-46db-8da3-bbbe1795f4c5"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"

[compat]
ComputableGeneralEquilibriumHelpers = "0.1.0"
Ipopt = "1.7.1"
JLD2 = "0.5.11"
JuMP = "1.23.6"
NamedArrays = "0.10.3"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
